"""Structured study-material generator.

Produces revision material as structured data rather than prose, so the
frontend can render a study card: overview, key concepts, notes, practice
questions, answers and further reading.

Content is generated by the model, which is correct here: revision material is
knowledge work, not a lookup. The one thing this must not do is invent
citations, so `furtherReading` is constrained to well-known, checkable
references and the prompt forbids invented URLs.
"""
from __future__ import annotations

import json
import logging
from typing import Any, Optional

from ..config.settings import Settings
from .base import PermissionLevel, Tool, ToolResult

logger = logging.getLogger(__name__)

_STUDY_PROMPT = """\
Create revision material for a student.

Topic: {topic}
Level: {level}
Language: {language}
{focus_line}

Return ONLY a JSON object with this exact shape:
{{
  "topic": "...",
  "level": "...",
  "overview": "two or three sentences on what this covers and why it matters",
  "keyConcepts": [{{"term": "...", "explanation": "..."}}],
  "notes": ["one paragraph per note"],
  "practiceQuestions": [{{"question": "...", "answer": "...", "explanation": "..."}}],
  "furtherReading": ["a named book, standard or website, described in one line"]
}}

Rules:
- "practiceQuestions" must contain at least {min_questions} items.
- Every question must have a complete answer and a short explanation.
- "furtherReading" must list real, widely known sources by name. Never invent
  a URL, an ISBN or a paper that does not exist.
- Write in {language}.
"""

_LEVELS = ("primary", "secondary", "undergraduate", "certificate", "postgraduate")


class StudyGeneratorTool(Tool):
    """Generate structured revision material for a topic."""

    name = "study_generator"
    description = (
        "Generate structured revision material for a subject: an overview, key "
        "concepts, notes, practice questions with answers and further reading. "
        "Use this when a student asks for revision, practice questions, a quiz, "
        "exam prep or study notes on a topic."
    )
    permission = PermissionLevel.SAFE
    requires_network = False

    input_schema = {
        "type": "object",
        "properties": {
            "topic": {
                "type": "string",
                "minLength": 2,
                "maxLength": 160,
                "description": "The subject to revise, e.g. 'human anatomy'.",
            },
            "level": {
                "type": "string",
                "enum": list(_LEVELS),
                "default": "secondary",
                "description": "Academic level, which changes the depth.",
            },
            "focus": {
                "type": "string",
                "maxLength": 200,
                "description": "Optional narrow topic, e.g. 'thermodynamics laws'.",
            },
            "language": {
                "type": "string",
                "maxLength": 10,
                "default": "en",
                "description": "Language code for the material.",
            },
            "questionCount": {
                "type": "integer",
                "minimum": 3,
                "maximum": 20,
                "default": 8,
                "description": "How many practice questions to produce.",
            },
        },
        "required": ["topic"],
    }

    output_schema = {
        "type": "object",
        "properties": {
            "topic": {"type": "string"},
            "level": {"type": "string"},
            "overview": {"type": "string"},
            "keyConcepts": {"type": "array"},
            "notes": {"type": "array"},
            "practiceQuestions": {"type": "array"},
            "furtherReading": {"type": "array"},
        },
    }

    def __init__(self, settings: Optional[Settings] = None):
        from ..config.settings import get_settings

        self.settings = settings or get_settings()

    async def run(self, arguments: dict) -> ToolResult:
        """Generate study material for a topic.

        Args:
            arguments: ``topic`` and optional ``level``, ``focus``,
                ``language`` and ``questionCount``.

        Returns:
            A ToolResult whose ``data`` is the structured material, or a
            failure when the model is unreachable.
        """
        topic = (arguments.get("topic") or "").strip()
        if not topic:
            return ToolResult(tool=self.name, ok=False, error="topic is required")

        level = str(arguments.get("level") or "secondary").lower()
        if level not in _LEVELS:
            level = "secondary"
        focus = (arguments.get("focus") or "").strip()
        language = (arguments.get("language") or "en").strip() or "en"
        try:
            question_count = max(3, min(20, int(arguments.get("questionCount") or 8)))
        except (TypeError, ValueError):
            question_count = 8

        prompt = _STUDY_PROMPT.format(
            topic=topic,
            level=level,
            language=language,
            focus_line=f"Focus specifically on: {focus}" if focus else "",
            min_questions=min(5, question_count),
        )

        from ..integrations.groq import GroqClient, GroqError

        client = GroqClient(self.settings)
        if not client.configured:
            return ToolResult(
                tool=self.name,
                ok=False,
                error="No model is configured to generate study material.",
            )

        try:
            raw = await client.complete_text(prompt, temperature=0.4, max_tokens=2600)
        except GroqError as exc:
            logger.warning("study_generator failed: %s", exc.status)
            return ToolResult(
                tool=self.name,
                ok=False,
                error="Study material could not be generated right now. Please try again.",
            )

        material = _parse_material(raw)
        if material is None:
            return ToolResult(
                tool=self.name,
                ok=False,
                error="Study material could not be generated right now. Please try again.",
            )

        material.setdefault("topic", topic)
        material.setdefault("level", level)
        material["questionCount"] = len(material.get("practiceQuestions") or [])
        logger.info(
            "study_generator topic=%r level=%s questions=%d",
            topic, level, material["questionCount"],
        )
        return ToolResult(tool=self.name, ok=True, data=material)


def _parse_material(raw: str) -> Optional[dict[str, Any]]:
    """Extract the study object from a model reply, or return None."""
    if not raw:
        return None
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end <= start:
        return None
    try:
        payload = json.loads(raw[start : end + 1])
    except json.JSONDecodeError:
        logger.warning("study_generator returned invalid JSON")
        return None
    if not isinstance(payload, dict):
        return None
    return payload
